### ISSUE TITLE
TypeError: Cannot read property 'relationships' of undefined

### ISSUE THREAD

**Issue by Jengas** [ickerio/pubg.js#3]
``    at Client.client.on (C:\Users\Jengas\Desktop\pubg-api\index.js:24:29)
    at Client.emit (events.js:180:13)
    at MessageCreateHandler.handle (C:\Users\Jengas\Desktop\pubg-api\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Jengas\Desktop\pubg-api\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Jengas\Desktop\pubg-api\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Jengas\Desktop\pubg-api\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Jengas\Desktop\pubg-api\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:180:13)
    at Receiver._receiver.onmessage (C:\Users\Jengas\Desktop\pubg-api\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (C:\Users\Jengas\Desktop\pubg-api\node_modules\ws\lib\receiver.js:409:14)``

The code is the same as in example page

**Comment by ickerio** [comment]
From what I see, this is not an issue with pubg.js but discord.js. Closed.
